# Generated by Django 4.2rc1 on 2023-04-03 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_alter_pricingtierproductprice_pricing_tier"),
        ("girvi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanitem",
            name="itemtype",
        ),
        migrations.RemoveField(
            model_name="loanitem",
            name="itemvalue",
        ),
        migrations.RemoveField(
            model_name="loanitem",
            name="purity",
        ),
        migrations.AlterField(
            model_name="loanitem",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.productvariant",
            ),
        ),
    ]
