# Generated by Django 4.2.3 on 2024-02-15 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("girvi", "0001_initial"),
        ("contact", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="license",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="girvi.license"
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="loan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="release",
                to="girvi.loan",
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="released_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="released_by",
                to="contact.customer",
            ),
        ),
        migrations.AddField(
            model_name="loanpayment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loanpayment",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_payments",
                to="girvi.loan",
            ),
        ),
        migrations.AddField(
            model_name="loanitem",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loanitems",
                to="girvi.loan",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contact.customer"
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="girvi.series"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="series",
            unique_together={("license", "name")},
        ),
    ]
