# Generated by Django 4.1.5 on 2023-02-21 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_alter_customer_pic"),
        ("girvi", "0002_loanitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticeItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="girvi.loan"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("D", "Draft"),
                            ("S", "Sent"),
                            ("A", "Acknowledged"),
                            ("R", "Responded"),
                        ],
                        default="D",
                        max_length=1,
                    ),
                ),
                (
                    "notice_type",
                    models.CharField(
                        choices=[("P", "Post"), ("W", "Whatsapp")],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact.customer",
                    ),
                ),
            ],
        ),
    ]
