# Generated by Django 4.2.3 on 2023-08-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="itemdesc",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Item"
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="releaseid",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
