# Generated by Django 2.1.3 on 2019-02-04 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0002_auto_20190204_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Customer'),
        ),
        migrations.AlterField(
            model_name='release',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='girvi.Loan'),
        ),
        migrations.AlterField(
            model_name='release',
            name='releaseid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
