# Generated by Django 4.2.3 on 2024-02-15 11:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="desc",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="uuid",
        ),
        migrations.RemoveField(
            model_name="loanpayment",
            name="desc",
        ),
        migrations.RemoveField(
            model_name="loanpayment",
            name="uuid",
        ),
    ]
