# Generated by Django 4.2rc1 on 2023-04-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0002_remove_loanitem_itemtype_remove_loanitem_itemvalue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanitem",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loanitems",
                to="girvi.loan",
            ),
        ),
    ]
