# Generated by Django 4.1.5 on 2023-02-27 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0003_noticeitem_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="noticeitem",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="noticeitem",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="noticeitem",
            name="notice",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="girvi.notice",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notice",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
