# Generated by Django 2.1.3 on 2019-02-04 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0003_auto_20190204_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girvi.Loan', unique=True),
        ),
    ]
