# Generated by Django 4.2.3 on 2023-08-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0003_alter_loan_itemdesc_alter_release_releaseid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="loanamount",
            field=models.PositiveIntegerField(default=0, verbose_name="Amount"),
        ),
        migrations.AlterField(
            model_name="loanitem",
            name="interest",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
