# Generated by Django 4.2.3 on 2023-09-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("girvi", "0004_alter_loan_loanamount_alter_loanitem_interest"),
        ("girvi", "0005_remove_loan_interestrate_remove_loan_itemvalue_and_more"),
        ("girvi", "0006_loanitem_itemdesc_loanitem_itemtype_loanitem_pic"),
        ("girvi", "0007_alter_loan_interest_alter_loan_loan_type"),
        ("girvi", "0008_remove_loan_itemtype"),
        ("girvi", "0009_loan_interestrate_loan_itemtype_loan_itemweight"),
        ("girvi", "0010_remove_loan_interestrate"),
        ("girvi", "0011_remove_loanitem_item"),
    ]

    dependencies = [
        ("girvi", "0003_alter_loan_itemdesc_alter_release_releaseid"),
        ("product", "0004_auto_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="loanamount",
            field=models.PositiveIntegerField(default=0, verbose_name="Amount"),
        ),
        migrations.AlterField(
            model_name="loanitem",
            name="interest",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RemoveField(
            model_name="loan",
            name="interestrate",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="itemvalue",
        ),
        # migrations.RemoveField(
        #     model_name="loan",
        #     name="itemweight",
        # ),
        migrations.AlterField(
            model_name="loan",
            name="loanamount",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="loanitem",
            name="interest",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="loanitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="loanitem",
            name="itemdesc",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Item"
            ),
        ),
        migrations.AddField(
            model_name="loanitem",
            name="itemtype",
            field=models.CharField(
                choices=[("Gold", "Gold"), ("Silver", "Silver"), ("Bronze", "Bronze")],
                default="Gold",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="loanitem",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to="loan_pics/"),
        ),
        migrations.AlterField(
            model_name="loan",
            name="interest",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_type",
            field=models.CharField(
                blank=True,
                choices=[("Taken", "Taken"), ("Given", "Given")],
                default="Given",
                max_length=10,
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="loan",
            name="itemtype",
        ),
        migrations.AddField(
            model_name="loan",
            name="itemtype",
            field=models.CharField(
                choices=[
                    ("Gold", "Gold"),
                    ("Silver", "Silver"),
                    ("Bronze", "Bronze"),
                    ("Mixed", "Mixed"),
                ],
                default="Gold",
                max_length=30,
            ),
        ),
        # migrations.AddField(
        #     model_name="loan",
        #     name="itemweight",
        #     field=models.DecimalField(
        #         blank=True,
        #         decimal_places=2,
        #         default=0,
        #         max_digits=10,
        #         null=True,
        #         verbose_name="Weight",
        #     ),
        # ),
        migrations.RemoveField(
            model_name="loanitem",
            name="item",
        ),
    ]
