# Generated by Django 4.2rc1 on 2023-04-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0003_alter_loanitem_loan"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="has_collateral",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loan",
            name="loan_type",
            field=models.CharField(
                choices=[("Taken", "Taken"), ("Given", "Given")],
                default="Given",
                max_length=10,
            ),
        ),
    ]
