# Generated by Django 4.2rc1 on 2023-04-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0004_loan_has_collateral_loan_loan_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="interest",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="interestrate",
            field=models.PositiveSmallIntegerField(default=2, verbose_name="ROI"),
        ),
        migrations.AlterField(
            model_name="loan",
            name="itemvalue",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, null=True, verbose_name="Value"
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loanamount",
            field=models.PositiveIntegerField(verbose_name="Amount"),
        ),
    ]
