# Generated by Django 2.1.3 on 2019-02-04 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0004_auto_20190204_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releasedby', to='contact.Customer'),
        ),
        migrations.AlterField(
            model_name='release',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release', to='girvi.Loan'),
        ),
    ]
