# Generated by Django 4.1.5 on 2023-02-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0004_notice_last_updated_noticeitem_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="medium_type",
            field=models.CharField(
                choices=[("P", "Post"), ("W", "Whatsapp")], default="P", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="notice_type",
            field=models.CharField(
                choices=[
                    ("FR", "First Reminder"),
                    ("SR", "Second Reminder"),
                    ("FN", "Final Notice"),
                ],
                default="FR",
                max_length=2,
            ),
        ),
    ]
