# Generated by Django 2.1.3 on 2019-02-04 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0005_auto_20190204_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
