# Generated by Django 4.1.5 on 2023-03-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0005_notice_medium_type_alter_notice_notice_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanitem",
            name="rate",
        ),
        migrations.RemoveField(
            model_name="notice",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="notice",
            name="status",
        ),
        migrations.AddField(
            model_name="noticeitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("D", "Draft"),
                    ("S", "Sent"),
                    ("A", "Acknowledged"),
                    ("R", "Responded"),
                ],
                default="D",
                max_length=1,
            ),
        ),
    ]
