# Generated by Django 4.2rc1 on 2023-04-14 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0005_alter_loan_interest_alter_loan_interestrate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loanitem",
            old_name="qty",
            new_name="quantity",
        ),
        migrations.RemoveField(
            model_name="adjustment",
            name="posted",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="posted",
        ),
        migrations.RemoveField(
            model_name="release",
            name="posted",
        ),
    ]
