# Generated by Django 4.2.3 on 2023-08-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0006_loanitem_itemdesc_loanitem_itemtype_loanitem_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="interest",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_type",
            field=models.CharField(
                blank=True,
                choices=[("Taken", "Taken"), ("Given", "Given")],
                default="Given",
                max_length=10,
                null=True,
            ),
        ),
    ]
