# Generated by Django 2.1.3 on 2019-02-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0006_auto_20190204_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='release',
            name='slug',
        ),
    ]
