# Generated by Django 4.1.5 on 2023-03-03 05:03

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0007_notification_remove_noticeitem_loan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticeGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("date_range", django.contrib.postgres.fields.ranges.DateRangeField()),
            ],
        ),
        migrations.AlterField(
            model_name="notification",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="girvi.loan",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notification",
            unique_together={("loan", "notice_type")},
        ),
        migrations.AddField(
            model_name="notification",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notice_items",
                to="girvi.noticegroup",
            ),
        ),
    ]
