# Generated by Django 4.2.3 on 2023-08-21 04:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0007_alter_loan_interest_alter_loan_loan_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="itemtype",
        ),
    ]
