# Generated by Django 4.1.5 on 2023-03-05 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0008_noticegroup_alter_notification_loan_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notification",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="notification",
            name="group",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="loan",
        ),
        migrations.DeleteModel(
            name="NoticeGroup",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
