# Generated by Django 2.2.2 on 2019-08-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0008_auto_20190329_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='itemdesc',
            field=models.TextField(max_length=100),
        ),
    ]
