# Generated by Django 4.2.3 on 2023-08-21 05:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0009_loan_interestrate_loan_itemtype_loan_itemweight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="interestrate",
        ),
    ]
