# Generated by Django 2.2.2 on 2019-08-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0009_auto_20190827_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='customer',
        ),
        migrations.AlterField(
            model_name='release',
            name='interestpaid',
            field=models.IntegerField(default=0),
        ),
    ]
