# Generated by Django 2.2.9 on 2020-04-20 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0010_auto_20190829_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount_received', models.IntegerField(default=0)),
                ('as_interest', models.BooleanField(default=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girvi.Loan')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
