# Generated by Django 4.2.3 on 2023-09-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "girvi",
            "0004_alter_loan_loanamount_alter_loanitem_interest_squashed_0011_remove_loanitem_item",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={"get_latest_by": "id", "ordering": ("series", "lid")},
        ),
        migrations.AddField(
            model_name="loan",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to="loan_pics/"),
        ),
        migrations.AlterField(
            model_name="loan",
            name="itemweight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Weight",
            ),
        ),
    ]
