# Generated by Django 2.2.9 on 2020-04-20 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0011_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='girvi.Loan'),
        ),
    ]
