# Generated by Django 4.2.3 on 2023-09-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0012_alter_loan_options_loan_pic_alter_loan_itemweight"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanitem",
            name="purity",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=75, max_digits=10, null=True
            ),
        ),
    ]
