# Generated by Django 2.2.9 on 2020-05-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0012_auto_20200420_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interestrate',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
