# Generated by Django 2.2.9 on 2020-05-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('girvi', '0013_auto_20200509_0718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ('-created', 'id')},
        ),
    ]
