# Generated by Django 4.2.3 on 2023-09-11 06:37

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0013_loanitem_purity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="created",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
