# Generated by Django 4.2.3 on 2023-09-13 04:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0014_alter_loan_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="itemtype",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="itemweight",
        ),
    ]
