# Generated by Django 4.2.3 on 2024-01-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0016_statement_statementitem_delete_loanstatement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="loanid",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
