# Generated by Django 4.2.3 on 2024-02-02 14:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0017_alter_loan_loanid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adjustment",
            options={"ordering": ("id",)},
        ),
        migrations.RenameField(
            model_name="loan",
            old_name="itemdesc",
            new_name="item_desc",
        ),
        migrations.RenameField(
            model_name="loan",
            old_name="loanamount",
            new_name="loan_amount",
        ),
        migrations.RenameField(
            model_name="loan",
            old_name="created",
            new_name="loan_date",
        ),
        migrations.RenameField(
            model_name="loan",
            old_name="loanid",
            new_name="loan_id",
        ),
        migrations.RemoveField(
            model_name="adjustment",
            name="created",
        ),
        migrations.RemoveField(
            model_name="adjustment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="updated",
        ),
        migrations.AddField(
            model_name="license",
            name="renewal_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="loan",
            name="series",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="girvi.series",
            ),
            preserve_default=False,
        ),
    ]
