# Generated by Django 4.2.3 on 2024-02-03 04:37

from django.db import migrations,models
import uuid

class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0020_auto_20240203_1007"),
    ]

    operations = [
        migrations.AlterField(
            model_name="Loan",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
