# Generated by Django 4.2.3 on 2024-02-07 10:04

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("girvi", "0021_auto_20240203_1007"),
    ]

    operations = [
        migrations.RenameField(
            model_name="release",
            old_name="created",
            new_name="release_date",
        ),
        migrations.RenameField(
            model_name="release",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="adjustment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adjustment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adjustment",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adjustment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="adjustment",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="release",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="release",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="release",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
