# Generated by Django 4.2.3 on 2024-02-07 10:06

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    adjustment = apps.get_model("girvi", "Adjustment")
    for row in adjustment.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])
    release = apps.get_model("girvi", "Release")
    for row in release.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0022_rename_created_release_release_date_and_more"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
