# Generated by Django 4.2.3 on 2024-02-07 10:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0023_auto_20240207_1536"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adjustment",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="release",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
