# Generated by Django 4.2.3 on 2024-02-08 04:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("girvi", "0024_auto_20240207_1536"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("desc", models.TextField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("payment_date", models.DateTimeField()),
                ("total_payment", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "principal_payment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "interest_payment",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_payments",
                        to="girvi.loan",
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
    ]
