# Generated by Django 4.2.3 on 2024-02-08 10:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("girvi", "0025_loanpayment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="release",
            old_name="releaseid",
            new_name="release_id",
        ),
        migrations.RemoveField(
            model_name="release",
            name="desc",
        ),
        migrations.RemoveField(
            model_name="release",
            name="interestpaid",
        ),
        migrations.RemoveField(
            model_name="release",
            name="uuid",
        ),
        migrations.AddField(
            model_name="release",
            name="loan_payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="girvi.loanpayment",
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="released_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="released_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="created_by",
            field=models.ForeignKey(
                default=8,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
