# Generated by Django 4.2.3 on 2024-02-08 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0005_alter_customer_relatedas_and_more"),
        ("girvi", "0026_rename_releaseid_release_release_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="released_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="released_by",
                to="contact.customer",
            ),
        ),
    ]
