# Generated by Django 4.2.3 on 2024-02-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0027_alter_release_released_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanpayment",
            name="total_payment",
        ),
        migrations.AddField(
            model_name="loanpayment",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Payment"
            ),
            preserve_default=False,
        ),
    ]
