# Generated by Django 4.2.3 on 2024-02-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0028_remove_loanpayment_total_payment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="release",
            name="loan_payment",
        ),
        migrations.AddField(
            model_name="loanpayment",
            name="with_release",
            field=models.BooleanField(default=False),
        ),
    ]
