# Generated by Django 4.2.3 on 2024-02-10 06:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0029_remove_release_loan_payment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="desc",
        ),
        migrations.DeleteModel(
            name="Adjustment",
        ),
    ]
