# Generated by Django 4.2.3 on 2024-02-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0030_remove_loan_desc_delete_adjustment"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
