# Generated by Django 4.2rc1 on 2023-03-29 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0014_alter_contact_phone_number"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockBalance",
            fields=[
                (
                    "stock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="product.stock",
                    ),
                ),
                ("Closing_wt", models.DecimalField(decimal_places=3, max_digits=14)),
                ("Closing_qty", models.IntegerField()),
                ("in_wt", models.DecimalField(decimal_places=3, max_digits=14)),
                ("in_qty", models.IntegerField()),
                ("out_wt", models.DecimalField(decimal_places=3, max_digits=14)),
                ("out_qty", models.IntegerField()),
            ],
            options={
                "db_table": "stock_balance",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=30)),
                ("direction", models.CharField(default="+", max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="StockLot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("qty", models.IntegerField(default=0)),
                ("wt", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=155,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "huid",
                    models.CharField(blank=True, max_length=6, null=True, unique=True),
                ),
                ("stock_code", models.CharField(max_length=4)),
                (
                    "purchase_touch",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                (
                    "purchase_rate",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("is_unique", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Empty", "Empty"),
                            ("Available", "Available"),
                            ("Sold", "Sold"),
                            ("Approval", "Approval"),
                            ("Return", "Return"),
                            ("Merged", "Merged"),
                        ],
                        default="Empty",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="stock",
            name="barcode",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="huid",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="melting",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="status",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="touch",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="tracking_type",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="wastage",
        ),
        migrations.RemoveField(
            model_name="stocktransaction",
            name="activity_type",
        ),
        migrations.RemoveField(
            model_name="stocktransaction",
            name="updated",
        ),
        migrations.AlterField(
            model_name="stock",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="product.productvariant",
            ),
        ),
        migrations.CreateModel(
            name="StockLotBalance",
            fields=[
                (
                    "lot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="product.stocklot",
                    ),
                ),
                ("Closing_wt", models.DecimalField(decimal_places=3, max_digits=14)),
                ("Closing_qty", models.IntegerField()),
                (
                    "in_wt",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=14),
                ),
                ("in_qty", models.IntegerField(default=0)),
                (
                    "out_wt",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=14),
                ),
                ("out_qty", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "stockbatch_balance",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="stocklot",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lots",
                to="product.stock",
            ),
        ),
        migrations.AddField(
            model_name="stocklot",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_lots",
                to="product.productvariant",
            ),
        ),
        migrations.CreateModel(
            name="PricingTier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("minimum_quantity", models.PositiveIntegerField()),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact.customer",
                    ),
                ),
                (
                    "price_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.pricingtier",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productvariant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stockstatement",
            name="lot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.stocklot",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="lot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.stocklot",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="movement_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.movement",
            ),
        ),
    ]
