# Generated by Django 3.2.5 on 2021-10-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20211006_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ('id',)},
        ),
    ]
