# Generated by Django 4.2rc1 on 2023-03-31 08:39

from django.db import migrations
from django.db.migrations.operations.base import Operation


class CreateView(Operation):
    reversible = True

    def __init__(self, name, sql):
        self.name = name
        self.sql = sql

    def state_forwards(self, app_label, state):
        pass

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        schema_editor.execute(f"CREATE VIEW {self.name} AS {self.sql}")

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        schema_editor.execute(f"DROP VIEW IF EXISTS {self.name};")

    def describe(self):
        return "Creates VIEW %s" % self.name

    @property
    def migration_name_fragment(self):
        return "create_view_%s" % self.name


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_auto_20230331_1406"),
    ]
    stock_balance_sql_v1 = """
        WITH stock_st AS
            (	
                select distinct on(stock_id) * 
                from product_stockstatement
                order by stock_id ,created desc
            )
        SELECT 
            product_stock.id as stock_id,product_stock.created,
            reorderat,
            variant_id,stock_st.method as statement_method,
            stock_st.created as statement_created,
            Coalesce(stock_st."Closing_wt",0.0)as Closing_wt,Coalesce(stock_st."Closing_qty",0) as Closing_qty,
            Coalesce(stock_st.total_wt_in,0.0)as total_wt_in,Coalesce(stock_st.total_wt_out,0.0) as total_wt_out,
            Coalesce(stock_st.total_qty_in,0)as total_qty_in,Coalesce(stock_st.total_qty_out,0)as total_qty_out,   
		
            ( SELECT COALESCE(sum(product_stocktransaction.quantity), 0::bigint) AS sum
            FROM product_stocktransaction
            WHERE 
                product_stocktransaction.stock_id = product_stock.id 
                AND ((stock_st.created isnull) or product_stocktransaction.created >= stock_st.created or 1>0)
                AND (product_stocktransaction.movement_type_id::text = ANY (ARRAY['P'::character varying::text, 'SR'::character varying::text, 'AD'::character varying::text, 'AR'::character varying::text]))) AS in_qty,
            
            ( SELECT COALESCE(sum(product_stocktransaction.quantity), 0::bigint) AS sum
            FROM product_stocktransaction
            WHERE 
            product_stocktransaction.stock_id = product_stock.id 
                AND ((stock_st.created isnull) or product_stocktransaction.created >= stock_st.created or 1>0)
                AND (product_stocktransaction.movement_type_id::text <> ALL (ARRAY['P'::character varying::text, 'SR'::character varying::text, 'AD'::character varying::text, 'AR'::character varying::text]))) AS out_qty,
            
            ( SELECT COALESCE(sum(product_stocktransaction.weight), 0.0) AS sum
            FROM product_stocktransaction
            WHERE 
            product_stocktransaction.stock_id = product_stock.id 
                AND ((stock_st.created isnull) or product_stocktransaction.created >= stock_st.created ) 
                AND (product_stocktransaction.movement_type_id::text = ANY (ARRAY['P'::character varying::text, 'SR'::character varying::text, 'AD'::character varying::text, 'AR'::character varying::text]))) AS in_wt,
            
            ( SELECT COALESCE(sum(product_stocktransaction.weight), 0.0) AS sum
            FROM product_stocktransaction
            WHERE product_stocktransaction.stock_id = product_stock.id 
                AND ((stock_st.created isnull) or product_stocktransaction.created >= stock_st.created) 
                AND (product_stocktransaction.movement_type_id::text <> ALL (ARRAY['P'::character varying::text, 'SR'::character varying::text, 'AD'::character varying::text, 'AR'::character varying::text]))) AS out_wt
            
        FROM product_stock
        LEFT JOIN stock_st
        ON product_stock.id = stock_st.stock_id
        ORDER BY product_stock.id;
        """

    stock_balance_sql = """
        WITH ss AS (
            SELECT DISTINCT ON (product_stockstatement.stock_id) product_stockstatement.id,
                product_stockstatement.method,
                product_stockstatement.sstype,
                product_stockstatement.created,
                product_stockstatement."Closing_wt",
                product_stockstatement."Closing_qty",
                product_stockstatement.total_wt_in,
                product_stockstatement.total_wt_out,
                product_stockstatement.total_qty_in,
                product_stockstatement.total_qty_out,
                product_stockstatement.stock_id
            FROM product_stockstatement
            WHERE product_stockstatement.sstype::text = 'Stock'::text
            ORDER BY product_stockstatement.stock_id, product_stockstatement.created DESC
            )
        SELECT ss.stock_id,
            ss."Closing_wt",
            ss."Closing_qty",
            ( SELECT COALESCE(sum(product_stocktransaction.quantity), 0::bigint) AS sum
                FROM product_stocktransaction
                WHERE product_stocktransaction.stock_id = ss.stock_id AND product_stocktransaction.created >= ss.created AND (product_stocktransaction.movement_type_id::text = ANY (ARRAY['P'::character varying::text, 'SR'::character varying::text, 'AD'::character varying::text, 'AR'::character varying::text]))) AS in_qty,
            ( SELECT COALESCE(sum(product_stocktransaction.quantity), 0::bigint) AS sum
                FROM product_stocktransaction
                WHERE product_stocktransaction.stock_id = ss.stock_id AND product_stocktransaction.created >= ss.created AND (product_stocktransaction.movement_type_id::text <> ALL (ARRAY['P'::character varying::text, 'SR'::character varying::text, 'AD'::character varying::text, 'AR'::character varying::text]))) AS out_qty,
            ( SELECT COALESCE(sum(product_stocktransaction.weight), 0.0) AS sum
                FROM product_stocktransaction
                WHERE product_stocktransaction.stock_id = ss.stock_id AND product_stocktransaction.created >= ss.created AND (product_stocktransaction.movement_type_id::text = ANY (ARRAY['P'::character varying::text, 'SR'::character varying::text, 'AD'::character varying::text, 'AR'::character varying::text]))) AS in_wt,
            ( SELECT COALESCE(sum(product_stocktransaction.weight), 0.0) AS sum
                FROM product_stocktransaction
                WHERE product_stocktransaction.stock_id = ss.stock_id AND product_stocktransaction.created >= ss.created AND (product_stocktransaction.movement_type_id::text <> ALL (ARRAY['P'::character varying::text, 'SR'::character varying::text, 'AD'::character varying::text, 'AR'::character varying::text]))) AS out_wt
        FROM ss;
        """

    stockbatch_balance_sql = """
          WITH ss AS (
         SELECT DISTINCT ON (product_stockstatement.lot_id) product_stockstatement.id,
            product_stockstatement.method,
           
            product_stockstatement.created,
            product_stockstatement."Closing_wt",
            product_stockstatement."Closing_qty",
            product_stockstatement.total_wt_in,
            product_stockstatement.total_wt_out,
            product_stockstatement.total_qty_in,
            product_stockstatement.total_qty_out,
            product_stockstatement.stock_id,
            product_stockstatement.lot_id
           FROM product_stockstatement
          
          ORDER BY product_stockstatement.lot_id, product_stockstatement.created DESC
        )
        SELECT sb.stock_id,
            sb.id AS lot_id,
            COALESCE(ss."Closing_wt", 0.0) AS "Closing_wt",
            COALESCE(ss."Closing_qty", 0) AS "Closing_qty",
            ( SELECT COALESCE(sum(product_stocktransaction.quantity), 0::bigint) AS sum
                FROM product_stocktransaction
                WHERE product_stocktransaction.lot_id = sb.id AND (ss.created IS NULL OR product_stocktransaction.created >= ss.created) AND (product_stocktransaction.movement_type_id::text = ANY (ARRAY['P'::character varying::text, 'SR'::character varying::text, 'AD'::character varying::text, 'AR'::character varying::text]))) AS in_qty,
            ( SELECT COALESCE(sum(product_stocktransaction.quantity), 0::bigint) AS sum
                FROM product_stocktransaction
                WHERE product_stocktransaction.lot_id = sb.id AND (ss.created IS NULL OR product_stocktransaction.created >= ss.created) AND (product_stocktransaction.movement_type_id::text <> ALL (ARRAY['P'::character varying::text, 'SR'::character varying::text, 'AD'::character varying::text, 'AR'::character varying::text]))) AS out_qty,
            ( SELECT COALESCE(sum(product_stocktransaction.weight), 0.0) AS sum
                FROM product_stocktransaction
                WHERE product_stocktransaction.lot_id = sb.id AND (ss.created IS NULL OR product_stocktransaction.created >= ss.created) AND (product_stocktransaction.movement_type_id::text = ANY (ARRAY['P'::character varying::text, 'SR'::character varying::text, 'AD'::character varying::text, 'AR'::character varying::text]))) AS in_wt,
            ( SELECT COALESCE(sum(product_stocktransaction.weight), 0.0) AS sum
                FROM product_stocktransaction
                WHERE product_stocktransaction.lot_id = sb.id AND (ss.created IS NULL OR product_stocktransaction.created >= ss.created) AND (product_stocktransaction.movement_type_id::text <> ALL (ARRAY['P'::character varying::text, 'SR'::character varying::text, 'AD'::character varying::text, 'AR'::character varying::text]))) AS out_wt
        FROM product_stocklot sb
            LEFT JOIN ss ON ss.lot_id = sb.id;
        """

    operations = [
        CreateView("stock_balance", stock_balance_sql_v1),
        CreateView("stockbatch_balance", stockbatch_balance_sql),
    ]
