# Generated by Django 4.2rc1 on 2023-03-29 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_stockstatement_lot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransaction",
            name="lot",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.stocklot",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="movement_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.movement",
            ),
        ),
    ]
