# Generated by Django 2.2.9 on 2020-03-25 08:34

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_stree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stree',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.Stree'),
        ),
    ]
