# Generated by Django 3.2.5 on 2021-10-28 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='movement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.movement'),
        ),
    ]
