# Generated by Django 4.2.3 on 2024-01-29 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0004_journalentry_alter_journal_options_and_more"),
        ("product", "0004_auto_views"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocktransaction",
            name="journal",
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="journal_entry",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stxns",
                to="dea.journalentry",
            ),
            preserve_default=False,
        ),
    ]
