# Generated by Django 3.2.5 on 2021-10-23 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211023_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('direction', models.CharField(default='+', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='movement_type',
            field=models.ForeignKey(default='P', on_delete=django.db.models.deletion.CASCADE, to='product.movement'),
            preserve_default=False,
        ),
    ]
