# Generated by Django 4.2.3 on 2024-02-16 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_auto_views"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rate",
        ),
        migrations.DeleteModel(
            name="RateSource",
        ),
    ]
