# Generated by Django 2.2.9 on 2020-03-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200325_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stree',
            name='barcode',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='stree',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
