# Generated by Django 4.2rc1 on 2023-03-29 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_stocktransaction_lot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransaction",
            name="movement_type",
            field=models.ForeignKey(
                default="P",
                on_delete=django.db.models.deletion.CASCADE,
                to="product.movement",
            ),
        ),
    ]
