# Generated by Django 3.2.5 on 2021-10-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20211023_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockbatch',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='stockbatch',
            old_name='wt',
            new_name='weight',
        ),
    ]
