# Generated by Django 2.2.9 on 2020-03-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200325_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='stree',
            name='tracking_type',
            field=models.CharField(choices=[('Lot', 'Lot'), ('Unique', 'Unique')], default='Lot', max_length=10),
        ),
    ]
