# Generated by Django 4.2rc1 on 2023-04-01 17:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_stocklot_purchase_stocklot_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocklot",
            name="sale",
        ),
    ]
