# Generated by Django 2.2.9 on 2020-03-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200325_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='stree',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=75, max_digits=10),
        ),
    ]
