# Generated by Django 3.2.5 on 2021-10-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20211023_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'stock_balance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockBatchBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'stockbatch_balance',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='stockstatement',
            name='sstype',
            field=models.CharField(choices=[('Stock', 'Stock'), ('Stockbatch', 'Stockbatch')], default='Stock', max_length=20),
        ),
        migrations.AddField(
            model_name='stockstatement',
            name='stock_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.stockbatch'),
        ),
    ]
