# Generated by Django 4.2rc1 on 2023-04-02 08:15

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_remove_stocklot_sale"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricingtier",
            name="contact",
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="level",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="lft",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="parent_tier",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="product.pricingtier",
            ),
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="rght",
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="tree_id",
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pricingtier",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name="PricingTierProductPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=3, max_digits=13),
                ),
                ("selling_price", models.DecimalField(decimal_places=3, max_digits=13)),
                (
                    "pricint_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.pricingtier",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productvariant",
                    ),
                ),
            ],
        ),
    ]
