# Generated by Django 4.2rc1 on 2023-04-02 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_remove_pricingtier_contact_pricingtier_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricingtier",
            old_name="parent_tier",
            new_name="parent",
        ),
    ]
