# Generated by Django 2.2.9 on 2020-03-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_stree_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stree',
            name='tracking_type',
            field=models.CharField(choices=[('Lot', 'Lot'), ('Unique', 'Unique')], default='Lot', max_length=10, null=True),
        ),
    ]
