# Generated by Django 4.2rc1 on 2023-04-02 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_rename_parent_tier_pricingtier_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricingtierproductprice",
            old_name="pricint_tier",
            new_name="pricing_tier",
        ),
    ]
