# Generated by Django 2.2.9 on 2020-03-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200326_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stree',
            name='cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
