# Generated by Django 4.2rc1 on 2023-04-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_ratesource_rate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rate",
            old_name="rate",
            new_name="buying_rate",
        ),
        migrations.AddField(
            model_name="rate",
            name="selling_rate",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
