# Generated by Django 4.2rc1 on 2023-04-03 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_rename_rate_rate_buying_rate_rate_selling_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricingtierproductprice",
            name="pricing_tier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_list",
                to="product.pricingtier",
            ),
        ),
    ]
