# Generated by Django 4.2rc1 on 2023-04-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_alter_pricingtierproductprice_pricing_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocklot",
            name="stock_code",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
