# Generated by Django 2.2.9 on 2020-03-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200326_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stree',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
