# Generated by Django 4.2rc1 on 2023-04-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0013_alter_stocklot_stock_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="currency",
            field=models.CharField(
                choices=[("INR", "INR"), ("USD", "USD")], default="INR", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="metal",
            field=models.CharField(
                choices=[("Gold", "Gold"), ("Silver", "Silver")],
                default="Gold",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="rate",
            name="purity",
            field=models.CharField(
                choices=[
                    ("24k", "24K"),
                    ("22k", "22K"),
                    ("18k", "18K"),
                    ("14k", "14K"),
                    ("10k", "10K"),
                ],
                default="24k",
                max_length=3,
            ),
        ),
    ]
