# Generated by Django 2.2.9 on 2020-03-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200326_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stree',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='stree',
            name='barcode',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
