# Generated by Django 4.2rc1 on 2023-04-14 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_alter_rate_currency_alter_rate_metal_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stocklot",
            old_name="qty",
            new_name="quantity",
        ),
        migrations.RenameField(
            model_name="stocklot",
            old_name="wt",
            new_name="weight",
        ),
    ]
