# Generated by Django 2.2.9 on 2020-03-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20200328_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stree',
            name='barcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
