# Generated by Django 4.2rc1 on 2023-04-16 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0008_alter_journal_content_type"),
        ("product", "0015_rename_qty_stocklot_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransaction",
            name="journal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stxns",
                to="dea.journal",
            ),
        ),
    ]
