# Generated by Django 4.2rc1 on 2023-04-16 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0007_alter_invoiceitem_invoice"),
        ("product", "0017_alter_stocklot_purchase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocklot",
            name="purchase",
        ),
        migrations.AddField(
            model_name="stocklot",
            name="purchase_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="purchase.invoiceitem",
            ),
        ),
    ]
