# Generated by Django 2.2.9 on 2020-03-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20200330_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='stree',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
