# Generated by Django 2.2.9 on 2020-03-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_stree_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stree',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Approval', 'Approval'), ('Return', 'Return')], default='Available', max_length=10),
        ),
    ]
