# Generated by Django 2.2.9 on 2020-03-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_stree_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stree',
            name='status',
            field=models.CharField(choices=[('Empty', 'Empty'), ('Available', 'Available'), ('Sold', 'Sold'), ('Approval', 'Approval'), ('Return', 'Return')], default='Empty', max_length=10),
        ),
    ]
