# Generated by Django 4.2rc1 on 2023-04-30 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0014_remove_paymentallocation_allocated_amount_and_more"),
        ("product", "0020_alter_stocklot_purchase_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocklot",
            name="purchase_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_lots",
                to="purchase.invoiceitem",
            ),
        ),
    ]
