# Generated by Django 2.2.9 on 2020-04-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20200331_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='stree',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
