# Generated by Django 3.2.5 on 2021-10-28 09:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=30)),
                ('amount', models.PositiveIntegerField()),
                ('commission', models.PositiveIntegerField()),
                ('member_limit', models.PositiveSmallIntegerField()),
                ('date_to_allot', models.DateField()),
                ('members', models.ManyToManyField(related_name='members', to='contact.Customer')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='contact.customer')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('installment', models.PositiveIntegerField()),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='to_member')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('chit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chitfund.chit')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.customer')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='member')),
                ('date_collected', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.PositiveIntegerField()),
                ('allotment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chitfund.allotment')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.customer')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
