# Generated by Django 3.2.5 on 2021-10-06 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20210925_1054'),
        ('Chitfund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='to_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.customer'),
        ),
        migrations.AlterField(
            model_name='chit',
            name='members',
            field=models.ManyToManyField(related_name='members', to='contact.Customer'),
        ),
        migrations.AlterField(
            model_name='chit',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='contact.customer'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.customer'),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
