# Generated by Django 3.0.7 on 2020-06-23 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('rate', models.PositiveSmallIntegerField(default=3000)),
                ('balancetype', models.CharField(choices=[('Cash', 'Cash'), ('Metal', 'Metal')], default='Metal', max_length=30)),
                ('paymenttype', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Credit', max_length=30)),
                ('balance', models.DecimalField(decimal_places=3, max_digits=10)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('PartiallyPaid', 'PartiallyPaid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=15)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='contact.Customer')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Cash', 'Cash'), ('Metal', 'Metal')], default='Cash', max_length=30, verbose_name='Currency')),
                ('rate', models.IntegerField(default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10)),
                ('touch', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('nettwt', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('description', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('Allotted', 'Allotted'), ('Partially Allotted', 'PartiallyAllotted'), ('Unallotted', 'Unallotted')], default='Unallotted', max_length=18)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='contact.Customer')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PaymentLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('touch', models.PositiveSmallIntegerField()),
                ('total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('is_return', models.BooleanField(default=False, verbose_name='Return')),
                ('quantity', models.IntegerField()),
                ('makingcharge', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseinvoices', to='purchase.Invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.ProductVariant')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
