# Generated by Django 4.2rc1 on 2023-04-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceitem",
            name="huid",
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="makingcharge",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="net_wt",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=10
            ),
        ),
    ]
