# Generated by Django 2.1.3 on 2018-12-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20181222_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='is_return',
            field=models.BooleanField(default=False, verbose_name='Return'),
        ),
    ]
