# Generated by Django 4.2.3 on 2024-01-29 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0004_journalentry_alter_journal_options_and_more"),
        ("purchase", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ("id", "created_at")},
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="created",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="id",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="created",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="updated",
        ),
        migrations.AddField(
            model_name="invoice",
            name="journal_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="dea.journal",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="journal_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="dea.journal",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paymentallocation",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paymentallocation_set",
                to="purchase.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="paymentallocation",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paymentallocation_set",
                to="purchase.payment",
            ),
        ),
    ]
