# Generated by Django 3.2.5 on 2021-09-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
