# Generated by Django 4.2rc1 on 2023-04-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0002_remove_invoiceitem_huid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="total",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10),
        ),
    ]
