# Generated by Django 3.2.5 on 2021-10-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_invoice_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='makingcharge',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='mc'),
        ),
    ]
