# Generated by Django 2.1.3 on 2018-12-24 07:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20181222_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Invoice')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='nettwt',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='touch',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Metal', 'Metal')], default='Cash', max_length=30, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='paymentline',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Payment'),
        ),
    ]
