# Generated by Django 2.1.3 on 2018-12-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20181224_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='balancetype',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Metal', 'Metal')], default='Cash', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paymenttype',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Cash', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Paid', 'Paid'), ('Partially Paid', 'partiallyPaid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=15),
        ),
    ]
