# Generated by Django 3.2.5 on 2021-10-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_invoiceitem_makingcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='makingcharge',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, verbose_name='mc'),
        ),
    ]
