# Generated by Django 4.2rc1 on 2023-04-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0004_invoicepaymentview_paymentallocation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="touch",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="weight",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
