# Generated by Django 4.2rc1 on 2023-04-14 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0005_alter_payment_touch_alter_payment_weight"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="type",
            new_name="payment_type",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="posted",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="posted",
        ),
    ]
