# Generated by Django 4.2rc1 on 2023-04-16 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0006_rename_type_payment_payment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_items",
                to="purchase.invoice",
            ),
        ),
    ]
