# Generated by Django 2.1.3 on 2018-12-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_auto_20181224_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Paid', 'Paid'), ('PartiallyPaid', 'PartiallyPaid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='makingcharge',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
