# Generated by Django 4.2rc1 on 2023-04-19 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contact", "0002_customer_pricing_tier"),
        ("purchase", "0007_alter_invoiceitem_invoice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoiceitem",
            old_name="makingcharge",
            new_name="making_charge",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="balancetype",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="gross_wt",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="metaltype",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="net_wt",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="rate",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="total",
        ),
        migrations.AddField(
            model_name="invoice",
            name="cash_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="gold_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="is_ratecut",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="silver_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="cash_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="hallmark_charge",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="metal_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="rate",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="contact.customer",
                verbose_name="Supplier",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="contact.customer",
                verbose_name="Supplier",
            ),
        ),
    ]
