# Generated by Django 2.1.3 on 2019-01-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_auto_20181226_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='balancetype',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Metal', 'Metal')], default='Metal', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paymenttype',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Credit', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='rate',
            field=models.PositiveSmallIntegerField(default=3000),
        ),
    ]
