# Generated by Django 4.2rc1 on 2023-04-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0008_rename_makingcharge_invoiceitem_making_charge_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceitem",
            name="total",
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="cash_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="hallmark_charge",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="making_charge",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="metal_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="rate",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
