# Generated by Django 2.1.3 on 2019-02-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_auto_20190102_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='paymentline',
            name='slug',
        ),
    ]
