# Generated by Django 4.2rc1 on 2023-04-21 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0009_remove_invoiceitem_total_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseBalance",
            fields=[
                (
                    "voucher",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="purchase.invoice",
                    ),
                ),
                ("cash_balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gold_balance", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "db_table": "purchase_balance",
                "managed": False,
            },
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="cash_balance",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="gold_balance",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="silver_balance",
        ),
    ]
