# Generated by Django 4.2rc1 on 2023-04-23 04:00

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0011_invoiceitem_cash_balance_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="cash_balance",
            field=djmoney.models.fields.MoneyField(
                decimal_places=3, default_currency="INR", max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="hallmark_charge",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="making_charge",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="metal_balance",
            field=djmoney.models.fields.MoneyField(
                decimal_places=3, default_currency="USD", max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="net_wt",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="rate",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="touch",
            field=models.DecimalField(decimal_places=3, max_digits=14),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="weight",
            field=models.DecimalField(decimal_places=3, max_digits=14),
        ),
    ]
