# Generated by Django 2.1.3 on 2018-11-30 07:24

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='contacts/customer/pic/')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('phonenumber', models.CharField(max_length=15)),
                ('Address', models.TextField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('Wh', 'Wholesale'), ('Re', 'Retail')], default='Re', max_length=30)),
                ('relatedas', models.CharField(choices=[('S/o', 'S/o'), ('D/o', 'D/o'), ('W/o', 'W/o'), ('R/o', 'R/o')], default='S/o', max_length=5)),
                ('relatedto', models.CharField(blank=True, max_length=30)),
                ('area', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='contacts/supplier/pic/')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('organisation', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=15)),
                ('initial', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
