# Generated by Django 4.1.5 on 2023-02-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to="customer_pics/"),
        ),
    ]
