# Generated by Django 4.2rc1 on 2023-04-02 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_remove_pricingtier_contact_pricingtier_description_and_more"),
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="pricing_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.pricingtier",
            ),
        ),
    ]
