# Generated by Django 3.2.5 on 2021-09-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactScore',
        ),
    ]
