# Generated by Django 4.1.5 on 2023-02-27 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_alter_customer_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proof",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proof_type", models.CharField(max_length=30)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("proof_no", models.CharField(max_length=30)),
                ("doc", models.FileField(upload_to="upload/files/proofs")),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "Customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("contact_type", models.CharField(max_length=30)),
                ("number", models.CharField(max_length=10)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "Customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactno",
                        to="contact.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=30)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("doorno", models.CharField(max_length=30)),
                ("zipcode", models.CharField(max_length=6)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("street", models.TextField(max_length=100)),
                (
                    "Customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact.customer",
                    ),
                ),
            ],
        ),
    ]
