# Generated by Django 4.2.3 on 2023-07-21 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_customer_pricing_tier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="Customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="contact.customer",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="area",
            field=models.CharField(default="ChinaAllapuram", max_length=30),
        ),
        migrations.AlterField(
            model_name="address",
            name="zipcode",
            field=models.CharField(default="632001", max_length=6),
        ),
        migrations.CreateModel(
            name="CustomerRelationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("S", "S/o"),
                            ("F", "F/o"),
                            ("D", "D/o"),
                            ("C", "C/o"),
                            ("W", "W/o"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_relationships",
                        to="contact.customer",
                    ),
                ),
                (
                    "related_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_customer_relationships",
                        to="contact.customer",
                    ),
                ),
            ],
        ),
    ]
