# Generated by Django 4.1.5 on 2023-02-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0003_proof_contact_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact_type",
            field=models.CharField(
                choices=[("H", "Home"), ("O", "Office"), ("M", "Mobile")],
                default="M",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="number",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
