# Generated by Django 4.2.3 on 2024-01-19 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0003_delete_contactscore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="relatedas",
            field=models.CharField(
                choices=[
                    ("s", "S/o"),
                    ("d", "D/o"),
                    ("w", "W/o"),
                    ("r", "R/o"),
                    ("f", "F/o"),
                    ("m", "M/o"),
                    ("h", "H/o"),
                    ("c", "C/o"),
                    ("b", "B/o"),
                    ("z", "Z/o"),
                    ("g", "G/o"),
                    ("n", "N/o"),
                    ("u", "U/o"),
                    ("a", "A/o"),
                    ("v", "V/o"),
                    ("e", "E/o"),
                    ("o", "O/o"),
                ],
                default="s",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="customerrelationship",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relationships",
                to="contact.customer",
            ),
        ),
        migrations.AlterField(
            model_name="customerrelationship",
            name="related_customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relatedby",
                to="contact.customer",
            ),
        ),
        migrations.AlterField(
            model_name="customerrelationship",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("s", "S/o"),
                    ("d", "D/o"),
                    ("w", "W/o"),
                    ("r", "R/o"),
                    ("f", "F/o"),
                    ("m", "M/o"),
                    ("h", "H/o"),
                    ("c", "C/o"),
                    ("b", "B/o"),
                    ("z", "Z/o"),
                    ("g", "G/o"),
                    ("n", "N/o"),
                    ("u", "U/o"),
                    ("a", "A/o"),
                    ("v", "V/o"),
                    ("e", "E/o"),
                    ("o", "O/o"),
                ],
                default="s",
                max_length=2,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customerrelationship",
            unique_together={("customer", "related_customer", "relationship")},
        ),
    ]
