# Generated by Django 4.1.5 on 2023-02-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0004_alter_contact_contact_type_alter_contact_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proof",
            name="proof_type",
            field=models.CharField(
                choices=[
                    ("AA", "AadharNo"),
                    ("DL", "Driving License"),
                    ("PN", "PanCard No"),
                ],
                default="AA",
                max_length=2,
            ),
        ),
    ]
