# Generated by Django 4.2.3 on 2024-01-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0004_alter_customer_relatedas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="relatedas",
            field=models.CharField(
                choices=[
                    ("s", "S/o"),
                    ("d", "D/o"),
                    ("f", "F/o"),
                    ("c", "C/o"),
                    ("p", "P/o"),
                    ("h", "H/o"),
                    ("w", "W/o"),
                    ("o", "O/o"),
                ],
                default="s",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="customerrelationship",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("s", "S/o"),
                    ("d", "D/o"),
                    ("f", "F/o"),
                    ("c", "C/o"),
                    ("p", "P/o"),
                    ("h", "H/o"),
                    ("w", "W/o"),
                    ("o", "O/o"),
                ],
                default="s",
                max_length=2,
            ),
        ),
    ]
