# Generated by Django 4.1.5 on 2023-02-27 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0005_alter_proof_proof_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="proof",
            options={"ordering": ("-created",)},
        ),
    ]
