# Generated by Django 2.2.9 on 2020-03-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_auto_20200314_1558'),
        ('contact', '0005_auto_20190323_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.AlterField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('Wh', 'Wholesale'), ('Re', 'Retail'), ('Su', 'Supplier')], default='Re', max_length=30),
        ),
    ]
