# Generated by Django 4.1.5 on 2023-02-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0006_alter_address_options_alter_contact_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="number",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
