# Generated by Django 4.1.5 on 2023-03-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0008_remove_customer_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.CharField(default="Vellore", max_length=30),
        ),
    ]
