# Generated by Django 4.1.5 on 2023-03-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0009_address_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="type",
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[("R", "Retail"), ("W", "Wholesale"), ("S", "Supplier")],
                default="R",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="relatedas",
            field=models.CharField(
                choices=[("s", "S/o"), ("d", "D/o"), ("w", "W/o"), ("r", "R/o")],
                default="s",
                max_length=5,
            ),
        ),
    ]
