# Generated by Django 4.1.5 on 2023-03-11 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0011_contact_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="Customer",
            new_name="customer",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="number",
        ),
    ]
