# Generated by Django 4.2.3 on 2023-07-23 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_wt",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("total_qty", models.IntegerField(default=0)),
                ("is_billed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Complete", "Complete"),
                            ("Billed", "Billed"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="ApprovalLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "weight",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                (
                    "touch",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Partially Returned", "Partially Returned"),
                            ("Returned", "Returned"),
                            ("Billed", "Billed"),
                        ],
                        default="Pending",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "ordering": ("approval",),
            },
        ),
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_wt",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("total_qty", models.IntegerField(default=0)),
                ("posted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "weight",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_items",
                        to="approval.approvalline",
                    ),
                ),
                (
                    "return_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="approval.return",
                    ),
                ),
            ],
        ),
    ]
