# Generated by Django 3.0.7 on 2020-06-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '__first__'),
        ('contact', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_wt', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('total_qty', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Invoiced', 'Invoiced'), ('Returned', 'Returned')], default='Pending', max_length=10)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='contact.Customer')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ApprovalReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_wt', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('total_qty', models.IntegerField(default=0)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.Approval')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ApprovalReturnLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('approvalreturn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.ApprovalReturn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Stree')),
            ],
            options={
                'ordering': ('approvalreturn',),
            },
        ),
        migrations.CreateModel(
            name='ApprovalLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('touch', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval.Approval')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.Stree')),
            ],
            options={
                'ordering': ('approval',),
            },
        ),
    ]
