# Generated by Django 4.2.3 on 2023-07-23 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("approval", "0001_initial"),
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="return",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_returns",
                to="contact.customer",
            ),
        ),
    ]
