# Generated by Django 4.2rc1 on 2023-04-08 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_invoicereceiptview_receiptallocation_and_more"),
        ("approval", "0004_return_returnlineitem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ReturnLineItem",
            new_name="ReturnItem",
        ),
        migrations.AddField(
            model_name="approvalline",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="approvalline",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Partially Returned", "Partially Returned"),
                    ("Returned", "Returned"),
                    ("Billed", "Billed"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="ApprovalLineReturn",
        ),
    ]
