# Generated by Django 4.2rc1 on 2023-04-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0005_rename_returnlineitem_returnitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnitem",
            name="posted",
            field=models.BooleanField(default=False),
        ),
    ]
