# Generated by Django 4.2rc1 on 2023-04-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0006_returnitem_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalline",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Pending", "Pending"),
                    ("Partially Returned", "Partially Returned"),
                    ("Returned", "Returned"),
                    ("Billed", "Billed"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
    ]
