# Generated by Django 4.2rc1 on 2023-04-14 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0007_alter_approvalline_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="approval",
            name="posted",
        ),
        migrations.RemoveField(
            model_name="returnitem",
            name="posted",
        ),
    ]
