# Generated by Django 4.2rc1 on 2023-04-16 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0008_remove_approval_posted_remove_returnitem_posted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="approvalline",
            name="invoice",
        ),
        migrations.AlterField(
            model_name="approvalline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lineitems",
                to="product.stocklot",
            ),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="line_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="return_items",
                to="approval.approvalline",
            ),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
