# Generated by Django 3.2.5 on 2021-10-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='voucher',
        ),
    ]
