# Generated by Django 3.2.5 on 2021-09-21 10:00

from dea.models import EntityType
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0001_initial'),
    ]
    
    def insertData(apps,schema_editor):
        entity = apps.get_model('dea','EntityType')
        
        person = entity(name='Person')
        person.save()
        org = entity(name = 'Organisation')
        org.save()

        transactiontype_de = apps.get_model('dea','TransactionType_DE')
        transactiontype_de.objects.create(XactTypeCode='Cr',name='Credit')
        transactiontype_de.objects.create(XactTypeCode='Dr', name='Debit')

        transactiontype_ext = apps.get_model('dea','TransactionType_Ext')
        transactiontype_ext.objects.create(XactTypeCode_ext='AC',description='Adjust Credit')
        transactiontype_ext.objects.create(XactTypeCode_ext='AD', description='Adjust Debit')
        transactiontype_ext.objects.create(XactTypeCode_ext='CPU', description='Cash Purchase')
        transactiontype_ext.objects.create(XactTypeCode_ext='CRPU', description='Credit Purchase')
        transactiontype_ext.objects.create(XactTypeCode_ext='CRSL', description='Credit Sale')
        transactiontype_ext.objects.create(XactTypeCode_ext='CSL', description='Cash Sale')
        transactiontype_ext.objects.create(XactTypeCode_ext='IP', description='Interest Paid')
        transactiontype_ext.objects.create(XactTypeCode_ext='IR', description='Interest Received')
        transactiontype_ext.objects.create(XactTypeCode_ext='LG', description='Loan Given')
        transactiontype_ext.objects.create(XactTypeCode_ext='LT', description='Loan Taken')
        transactiontype_ext.objects.create(XactTypeCode_ext='PYT', description='Payment')
        transactiontype_ext.objects.create(XactTypeCode_ext='RCT', description='Receipt')

        acc_type = apps.get_model('dea', 'AccountType')
        acc_type.objects.create(AccountType = 'Asset',description ='Asset')
        acc_type.objects.create(AccountType='Liability', description='Liabilities')
        acc_type.objects.create(AccountType='Equity', description='Equity')
        acc_type.objects.create(AccountType='Income', description='Income')
        acc_type.objects.create(AccountType='Expense', description='Expense')

        acc_type_ext = apps.get_model('dea','AccountType_Ext')
        acc_type_ext.objects.create(description='Creditor',XactTypeCode_id='Cr')
        acc_type_ext.objects.create(description='Debtor', XactTypeCode_id='Dr')

    operations = [
        migrations.RunPython(insertData),
    ]

    
