# Generated by Django 3.2.5 on 2021-10-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0003_dea_views'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['ledgerno'], name='dea_account_ledgern_eea025_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['ledgerno'], name='dea_ledgert_ledgern_b79320_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['ledgerno_dr'], name='dea_ledgert_ledgern_31d496_idx'),
        ),
    ]
