# Generated by Django 4.2rc1 on 2023-04-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0003_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="type",
            field=models.CharField(
                choices=[
                    ("Base Journal", "base journal"),
                    ("Loan Taken", "Loan taken"),
                    ("Loan Given", "Loan given"),
                    ("Loan Released", "Loan released"),
                    ("Loan Paid", "Loan paid"),
                    ("Interest Paid", "Interest Paid"),
                    ("Interest Received", "Interest Received"),
                    ("Sales", "Sales"),
                    ("Sales Return", "Sales Return"),
                    ("Receipt", "Receipt"),
                    ("Purchase", "Purchase"),
                    ("Purchase Return", "Purchase Return"),
                    ("Payment", "Payment"),
                    ("StockIN", "StockIN"),
                    ("StockOUT", "StockOUT"),
                ],
                default="Base Journal",
                max_length=50,
            ),
        ),
    ]
