# Generated by Django 4.2.3 on 2024-01-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0003_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("object_id", models.PositiveIntegerField()),
            ],
            options={
                "get_latest_by": "id",
            },
        ),
        migrations.RemoveField(
            model_name="journal",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="accounttransaction",
            name="journal",
        ),
        migrations.RemoveField(
            model_name="ledgertransaction",
            name="journal",
        ),
    ]
