# Generated by Django 3.2.5 on 2021-11-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0004_auto_20211006_1827'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountbalance',
            table='account_balance_v1',
        ),
        migrations.AlterModelTable(
            name='ledgerbalance',
            table='ledger_balance_v1',
        ),
    ]
