# Generated by Django 3.2.5 on 2021-10-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dea', '0004_auto_20211006_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='type',
            field=models.CharField(choices=[('Base Journal', 'base journal'), ('Loan Taken', 'Loan taken'), ('Loan Given', 'Loan given'), ('Loan Released', 'Loan released'), ('Loan Paid', 'Loan paid'), ('Interest Paid', 'Interest Paid'), ('Interest Received', 'Interest Received'), ('Sales', 'Sales'), ('Sales Return', 'Sales Return'), ('Receipt', 'Receipt'), ('Purchase', 'Purchase'), ('Purchase Return', 'Purchase Return'), ('Payment', 'Payment'), ('Stock', 'Stock')], default='Base Journal', max_length=50),
        ),
    ]
