# Generated by Django 4.2.3 on 2024-01-27 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0004_journalentry_remove_journal_content_type_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("product", "0005_remove_stocktransaction_journal_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Journal",
        ),
        migrations.AddField(
            model_name="journalentry",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="accounttransaction",
            name="journal_entry",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atxns",
                to="dea.journalentry",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ledgertransaction",
            name="journal_entry",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ltxns",
                to="dea.journalentry",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="dea_journal_content_9f6430_idx",
            ),
        ),
    ]
