# Generated by Django 4.2rc1 on 2023-04-08 05:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0005_remove_journal_type_journal_contact_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="contact",
        ),
    ]
