# Generated by Django 4.2rc1 on 2023-04-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dea", "0006_remove_journal_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="journal",
            name="journal_type",
            field=models.CharField(
                choices=[
                    ("LedgerJournal", "LedgerJournal"),
                    ("AccountJournal", "AccountJournal"),
                    ("StockJournal", "StockJournal"),
                ],
                default="LedgerJournal",
                max_length=50,
            ),
        ),
    ]
