# Generated by Django 4.2rc1 on 2023-04-16 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dea", "0007_journal_updated_alter_journal_journal_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
