# Generated by Django 4.2rc1 on 2023-04-16 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dea", "0009_alter_journal_object_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
    ]
