# Generated by Django 4.2rc1 on 2023-03-31 08:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0001_initial"),
        ("invoice", "0001_initial"),
        ("contact", "0001_initial"),
        ("approval", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated", models.DateTimeField(auto_now_add=True)),
                (
                    "rate",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("is_gst", models.BooleanField(default=False)),
                ("posted", models.BooleanField(default=False)),
                (
                    "gross_wt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "net_wt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=0.0,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=4, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("PartiallyPaid", "PartiallyPaid"),
                            ("Unpaid", "Unpaid"),
                        ],
                        default="Unpaid",
                        max_length=15,
                    ),
                ),
                (
                    "balancetype",
                    models.CharField(
                        choices=[("INR", "Cash"), ("USD", "Gold"), ("AUD", "Silver")],
                        default="INR",
                        max_length=30,
                        verbose_name="Bal_type",
                    ),
                ),
                (
                    "metaltype",
                    models.CharField(
                        choices=[("Gold", "Gold"), ("Silver", "Silver")],
                        default="Gold",
                        max_length=30,
                        verbose_name="Currency",
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approval",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bill",
                        to="approval.approval",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sold",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="contact.customer",
                    ),
                ),
                (
                    "term",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_term",
                        to="invoice.paymentterm",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "get_latest_by": "id",
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("INR", "Cash"), ("USD", "Gold"), ("AUD", "Silver")],
                        default="INR",
                        max_length=30,
                        verbose_name="Currency",
                    ),
                ),
                ("rate", models.IntegerField(default=0)),
                (
                    "total",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "description",
                    models.TextField(default="describe here", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Allotted", "Allotted"),
                            ("Partially Allotted", "PartiallyAllotted"),
                            ("Unallotted", "Unallotted"),
                        ],
                        default="Unallotted",
                        max_length=18,
                    ),
                ),
                ("posted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="contact.customer",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="ReceiptLine",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("amount", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.invoice"
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.receipt"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=3, default=0.0, max_digits=10
                    ),
                ),
                (
                    "touch",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                (
                    "nettwt",
                    models.DecimalField(
                        blank=True, decimal_places=3, default=0.0, max_digits=10
                    ),
                ),
                ("rate", models.IntegerField(default=0)),
                ("amount", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.receipt"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "huid",
                    models.CharField(blank=True, max_length=6, null=True, unique=True),
                ),
                ("quantity", models.IntegerField()),
                ("weight", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "less_stone",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=10,
                        verbose_name="less wt",
                    ),
                ),
                ("touch", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "wastage",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "net_wt",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                ("total", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "is_return",
                    models.BooleanField(default=False, verbose_name="Return"),
                ),
                (
                    "makingcharge",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saleitems",
                        to="sales.invoice",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="product.stocklot",
                    ),
                ),
            ],
            options={
                "ordering": ("-pk",),
            },
        ),
    ]
