# Generated by Django 4.1.5 on 2023-03-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="balancetype",
            field=models.CharField(
                choices=[("INR", "Cash"), ("USD", "Gold"), ("AUD", "Silver")],
                default="INR",
                max_length=30,
                verbose_name="Bal_type",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="gross_wt",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="metaltype",
            field=models.CharField(
                choices=[("Gold", "Gold"), ("Silver", "Silver")],
                default="Gold",
                max_length=30,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="net_wt",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0.0, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="less_stone",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=10, verbose_name="less wt"
            ),
        ),
    ]
