# Generated by Django 4.2rc1 on 2023-04-07 10:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_alter_invoiceitem_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceReceiptView",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "amount_allocated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "db_table": "sales_receipt_view",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReceiptAllocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.invoice"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="receiptline",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="receiptline",
            name="receipt",
        ),
        migrations.AddField(
            model_name="receipt",
            name="touch",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="receipt",
            name="weight",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name="ReceiptItem",
        ),
        migrations.DeleteModel(
            name="ReceiptLine",
        ),
        migrations.AddField(
            model_name="receiptallocation",
            name="receipt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sales.receipt"
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="invoices",
            field=models.ManyToManyField(
                through="sales.ReceiptAllocation", to="sales.invoice"
            ),
        ),
    ]
