# Generated by Django 2.1.3 on 2018-12-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20181222_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='nettwt',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receipt',
            name='touch',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='receipt',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
