# Generated by Django 4.2rc1 on 2023-04-08 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0005_rename_returnlineitem_returnitem_and_more"),
        ("sales", "0003_invoicereceiptview_receiptallocation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="approval_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="approval.approvalline",
            ),
        ),
    ]
