# Generated by Django 4.2rc1 on 2023-04-14 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_invoiceitem_approval_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipt",
            old_name="type",
            new_name="receipt_type",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="posted",
        ),
        migrations.RemoveField(
            model_name="receipt",
            name="posted",
        ),
    ]
