# Generated by Django 4.2rc1 on 2023-04-16 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0009_remove_approvalline_invoice_and_more"),
        ("sales", "0006_remove_invoiceitem_approval_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="approval.approval",
            ),
        ),
    ]
