# Generated by Django 4.2rc1 on 2023-04-16 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("approval", "0009_remove_approvalline_invoice_and_more"),
        ("sales", "0007_alter_invoice_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="approval_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sold_items",
                to="approval.approvalline",
            ),
        ),
    ]
