# Generated by Django 4.2rc1 on 2023-04-19 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_customer_pricing_tier"),
        ("sales", "0008_alter_invoiceitem_approval_line"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales",
                to="contact.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="contact.customer",
                verbose_name="Customer",
            ),
        ),
    ]
