# Generated by Django 2.1.3 on 2018-12-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20181223_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('created',)},
        ),
    ]
