# Generated by Django 4.2rc1 on 2023-04-29 04:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0010_salebalance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receiptallocation",
            name="allocated_amount",
        ),
    ]
