# Generated by Django 2.1.3 on 2018-12-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20181224_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='total',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
