# Generated by Django 2.1.3 on 2019-02-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_20190213_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='receiptline',
            name='slug',
        ),
    ]
