# Generated by Django 2.1.7 on 2019-03-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_auto_20190309_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='receipt',
            name='description',
            field=models.TextField(default='describe here', max_length=50),
        ),
    ]
