# Generated by Django 2.2.9 on 2020-03-27 12:27

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_auto_20200327_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Stree'),
        ),
    ]
