# Generated by Django 4.1.5 on 2023-03-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0009_alter_notification_unique_together_and_more"),
        ("notify", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notification",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_printed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="loans",
            field=models.ManyToManyField(to="girvi.loan"),
        ),
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.TextField(default="hello message"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="medium_type",
            field=models.CharField(
                choices=[
                    ("P", "Post"),
                    ("W", "Whatsapp"),
                    ("S", "SMS"),
                    ("L", "Letter"),
                ],
                default="P",
                max_length=1,
            ),
        ),
        migrations.RemoveField(
            model_name="notification",
            name="loan",
        ),
    ]
