# Generated by Django 4.2rc1 on 2023-04-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0007_alter_loan_itemdesc_alter_loan_itemweight"),
        ("notify", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="loans",
            field=models.ManyToManyField(related_name="notifications", to="girvi.loan"),
        ),
    ]
