# Generated by Django 4.1.5 on 2023-03-11 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0010_remove_customer_type_customer_customer_type_and_more"),
        ("notify", "0002_alter_notification_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="noticegroup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contact.customer",
            ),
            preserve_default=False,
        ),
    ]
