# Generated by Django 4.1.5 on 2023-03-11 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notify", "0003_noticegroup_description_notification_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="notify.noticegroup",
            ),
        ),
    ]
