# Generated by Django 4.1.5 on 2023-03-11 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0009_alter_notification_unique_together_and_more"),
        ("notify", "0004_alter_notification_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="notify.noticegroup",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="loans",
            field=models.ManyToManyField(related_name="notifications", to="girvi.loan"),
        ),
    ]
