# Generated by Django 4.1.5 on 2023-03-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("girvi", "0009_alter_notification_unique_together_and_more"),
        ("notify", "0005_alter_notification_group_alter_notification_loans"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="loans",
            field=models.ManyToManyField(to="girvi.loan"),
        ),
    ]
