# Generated by Django 4.1.5 on 2023-03-11 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notify", "0006_alter_notification_loans"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="noticegroup",
            name="date_range",
        ),
    ]
